### ISSUE TITLE
ImportError: libgrass_datetime.7.8.so: cannot open shared object file: No such file or directory on version 0.5

### ISSUE THREAD

**Issue by manuelep** [zarch/grass-session#22]
I found a problem that can be reproduced running the subsequent script (on py 3.9)

```py
# -*- coding: utf-8 -*-

import os, sys

GISBASE = '/usr/lib/grass78'
GRASSBIN = '/usr/bin/grass78'

# Define GRASS-Python environment
os.environ['GISBASE'] = GISBASE

os.environ['GRASSBIN'] = GRASSBIN

sys.path.append(os.path.join(GISBASE, "etc", "python"))

from grass_session import Session
import grass.script as gs

print(f"GRASSBIN: {os.environ['GRASSBIN']}")

with Session(gisdb="/tmp", location="location", create_opts="EPSG:4326"):
    print(f"LD_LIBRARY_PATH: {os.environ['LD_LIBRARY_PATH']}")
    from grass.pygrass.vector import Vector

print('DONE!')
```

using grass_session version 0.5 this exception is raised

```
Traceback (most recent call last):
  File "/usr/lib/grass78/etc/python/grass/lib/ctypes_loader.py", line 76, in load
    return ctypes.cdll.LoadLibrary(path)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libgrass_datetime.7.8.so: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/manuele/Lavoro/ETS/ETSCore/scripts/import_test.py", line 25, in <module>
    from grass.pygrass.vector import Vector
  File "/usr/lib/grass78/etc/python/grass/pygrass/vector/__init__.py", line 5, in <module>
    import grass.lib.gis as libgis
  File "/usr/lib/grass78/etc/python/grass/lib/gis.py", line 23, in <module>
    _libs["grass_gis.7.8"] = load_library("grass_gis.7.8")
  File "/usr/lib/grass78/etc/python/grass/lib/ctypes_loader.py", line 62, in load_library
    return self.load(path)
  File "/usr/lib/grass78/etc/python/grass/lib/ctypes_loader.py", line 78, in load
    raise ImportError(e)
ImportError: libgrass_datetime.7.8.so: cannot open shared object file: No such file or directory
```

while everything works fine downgrading grass_session to version 0.4

Thanks
Best regards

    Manuele

**Comment by manuelep** [comment]
Thanks to [Moritz advises](https://lists.osgeo.org/pipermail/grass-user/2021-August/082535.html) I discovered it was  just a matter of retro compatibility of the new Session init API, it was just enough to set `loadlibs=True` while instantiating the Session object for letting the script run without raising the exception.
I think I can close this issue.
