### ISSUE TITLE
Do not destroy location after use and reattach to existing Location

### ISSUE THREAD

**Issue by YannChemin** [zarch/grass-session#5]
Ciao Pietro !

I am running a code that needs to rerun several times the same processing in GRASS with different configurations, I would like to know if there are mechanism to have the session not remove the Location on exit and a way to get the grass session to reopen an existing Location.

Thanks,
Yann

**Comment by zarch** [comment]
Hi Yann,

Can you provide a small code example that highlight the issue?
The location is never removed from the grass-session, the only thing that is removed is the GISRC file:

```python
class Session():
    def close(self):
        """Close a GRASS Session."""
        if "GISRC" in self.env:
            self.env.pop("GIS_LOCK")
            os.remove(self.env.pop("GISRC"))

    def __enter__(self):
        self.open(*self._aopen, **self._kwopen)
        return self

    def __exit__(self, exc_type, exc_value, traceback):
         self.close()

```
https://github.com/zarch/grass-session/blob/master/grass_session/session.py#L246

If I tried on a shell I got:
```python
>>> with Session(gisdb="/tmp", location="location", mapset="test",                   
...              create_opts=""):
...    print(gcore.parse_command("g.gisenv", flags="s"))    
...    print(gcore.parse_command("g.region", flags="g"))    
 {u'MAPSET': u"'test';", u'GISDBASE': u"'/tmp';", u'LOCATION_NAME': u"'location';"}
{u'rows': u'1', u'e': u'1', u'projection': u'3', u'zone': u'0', u'cells': u'1', u'cols': u'1', u'n': u'1', u's': u'0', u'w': u'0', u'ewres': u'1', u'nsres': u'1'}
>>> with Session(gisdb="/tmp", location="location", mapset="test",                   
...              create_opts=""):
...    print(gcore.parse_command("g.gisenv", flags="s"))
...    print(gcore.parse_command("g.region", n=50, s=0, e=45, w=0, res=1, flags="g"))
{u'MAPSET': u"'test';", u'GISDBASE': u"'/tmp';", u'LOCATION_NAME': u"'location';"}
{u'rows': u'50', u'e': u'45', u'projection': u'3', u'zone': u'0', u'cells': u'2250', u'cols': u'45', u'n': u'50', u's': u'0', u'w': u'0', u'ewres': u'1', u'nsres': u'1'}
>>> with Session(gisdb="/tmp", location="location", mapset="test",                   
...              create_opts=""):
...    print(gcore.parse_command("g.gisenv", flags="s"))
...    print(gcore.parse_command("g.region", flags="g"))
{u'MAPSET': u"'test';", u'GISDBASE': u"'/tmp';", u'LOCATION_NAME': u"'location';"}
{u'rows': u'50', u'e': u'45', u'projection': u'3', u'zone': u'0', u'cells': u'2250', u'cols': u'45', u'n': u'50', u's': u'0', u'w': u'0', u'ewres': u'1', u'nsres': u'1'}
```
So as you can see the location/mapset is persistent.

**Comment by YannChemin** [comment]
Hi Pietro

>>> from grass_session import Session
>>> from grass.script import core as gcore
>>> with Session(gisdb="/tmp", location="location", mapset="test",create_opts=""):
...     print(gcore.parse_command("g.gisenv", flags="s")) 
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yann/.local/lib/python2.7/site-packages/grass_session/session.py", line 249, in __enter__
    self.open(*self._aopen, **self._kwopen)
  File "/home/yann/.local/lib/python2.7/site-packages/grass_session/session.py", line 235, in open
    self.create(path, create_opts=create_opts)
  File "/home/yann/.local/lib/python2.7/site-packages/grass_session/session.py", line 240, in create
    grass_create(self.grassbin, path, create_opts)
  File "/home/yann/.local/lib/python2.7/site-packages/grass_session/session.py", line 209, in grass_create
    out=out, err=err))
RuntimeError: Cannot create: /tmp/location/test with the following options: . Executing:
grass74 -c  -e /tmp/location/test
GRASS said:
Cleaning up temporary files...
Creating new GRASS GIS location/mapset...
ERROR: Failed to create new location. The location <test> already exists.
Exiting...


How can I reattach to this location?

**Comment by zarch** [comment]
Hi Yann,

sorry for the delay, so here the complete interactive python session:

```bash
➜  ~ GRASSBIN=/home/pietro/.local/bin/grass75 ipython2
WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
Python 2.7.15 (default, Jun 27 2018, 13:05:28) 
Type "copyright", "credits" or "license" for more information.

IPython 3.2.1 -- An enhanced Interactive Python.
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.

In [1]: from grass_session import Session                                             
GRASSBIN: /home/pietro/.local/bin/grass75
GISBASE: /home/pietro/.local/grass-7.5.svn

In [2]: from grass.script import core as gcore                                        

In [3]: # create a new mapset that does not exists: /tmp/location/test 
   ...: with Session(gisdb="/tmp", location="location", mapset="test", create_opts=""):
   ...:    print(gcore.parse_command("g.gisenv", flags="s"))
   ...:     
{u'MAPSET': u"'test';", u'GISDBASE': u"'/tmp';", u'LOCATION_NAME': u"'location';"}

In [4]: # try again to create aa new location that already exists
   ...: with Session(gisdb="/tmp", location="location", mapset="test", create_opts=""):
   ...:    print(gcore.parse_command("g.gisenv", flags="s"))
   ...:     
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-750f69cb8649> in <module>()
----> 1 with Session(gisdb="/tmp", location="location", mapset="test",create_opts=""):
      2     print(gcore.parse_command("g.gisenv", flags="s"))
      3 

/home/pietro/.local/lib/python2.7/site-packages/grass_session/session.pyc in __enter__(self)
    238 
    239     def __enter__(self):
--> 240         self.open(*self._aopen, **self._kwopen)
    241         return self
    242 

/home/pietro/.local/lib/python2.7/site-packages/grass_session/session.pyc in open(self, gisdb, location, mapset, create_opts, env)
    224             else:
    225                 path = os.path.join(gisdb, location, mapset)
--> 226             self.create(path, create_opts=create_opts)
    227         return grass_init(self.gisbase, gisdb, location, mapset, env=env)
    228 

/home/pietro/.local/lib/python2.7/site-packages/grass_session/session.pyc in create(self, path, create_opts)
    229     def create(self, path, create_opts):
    230         """Create a new mapset"""
--> 231         grass_create(self.grassbin, path, create_opts)
    232 
    233     def close(self):

/home/pietro/.local/lib/python2.7/site-packages/grass_session/session.pyc in grass_create(grassbin, path, create_opts)
    200                                                  create_opts=create_opts,
    201                                                  cmd=cmd,
--> 202                                                  out=out, err=err))
    203 
    204 

RuntimeError: Cannot create: /tmp/location/test with the following options: . Executing:
/home/pietro/.local/bin/grass75 -c  -e /tmp/location/test
GRASS said:

Cleaning up temporary files...
Creating new GRASS GIS location/mapset...
ERROR: Failed to create new location. The location <test> already exists.
Exiting...


In [5]: # open an existing mapset using:  create_opts=None
   ...: with Session(gisdb="/tmp", location="location", mapset="test", create_opts=None):
   ...:    print(gcore.parse_command("g.gisenv", flags="s"))
   ...:     
{u'MAPSET': u"'test';", u'GISDBASE': u"'/tmp';", u'LOCATION_NAME': u"'location';"}
```

The `create_opts` parameter accepts any valid string accepted by the `grass -c` flag therefore: `[geofile | EPSG]`

Therefore the above ipython session it is equivalent to:

```bash
➜  ~ grass75 -c /tmp/location/test_A -e
Cleaning up temporary files...
Creating new GRASS GIS location/mapset...
Cleaning up temporary files...
➜  ~ grass75 -c /tmp/location/test_A -e
Cleaning up temporary files...
Creating new GRASS GIS location/mapset...
ERROR: Failed to create new location. The location <test_A> already exists.
Exiting...

```
As you can see I have the same error message.

To fix the error, if the mapset has been already created you need to use the `create_opt=None` or simply not pass this parameter (the default value is None).

Let me know if, with this explanation, everything it works and it is clear.

**Comment by YannChemin** [comment]
Thank you Pietro,

that makes sense then

Cheers,
Yann
